In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [18]:
df1 = pd.read_excel('C:/bigcontest/data/gsretail/gsretail_data.xlsx', sheet_name=3, header=3) #동별매출지수
df2 = pd.read_excel('C:/bigcontest/data/gsretail/gsretail_data.xlsx', sheet_name=4) #카테고리별 매출비중
df3 = pd.read_excel('C:/bigcontest/data/gsretail/gsretail_data.xlsx', sheet_name=5) #종합테이블

In [19]:
df1.head()

,PVN,BOR,ADMD,20190201,20190202,20190203,20190204,20190205,20190206,20190207,...,20200522,20200523,20200524,20200525,20200526,20200527,20200528,20200529,20200530,20200531
0,전체,NaN,NaN,1.198007,1.017985,0.963684,0.918759,1.028130,0.900022,1.062491,...,1.080985,1.020417,0.885803,1.021254,1.067526,1.063149,1.076086,1.137684,1.045754,0.928725
1,서울특별시,NaN,NaN,1.188696,1.004386,0.953775,0.899579,1.036262,0.892765,1.079589,...,1.162798,1.078928,0.930147,1.098651,1.143194,1.147769,1.169708,1.226083,1.110484,0.978101
2,서울특별시,중구,NaN,1.379749,1.037523,1.013265,0.898529,1.003199,0.892831,1.264520,...,1.230307,0.998263,0.777919,1.186941,1.259630,1.243106,1.289460,1.295647,1.002761,0.849583
3,서울특별시,중구,소공동,1.668360,1.115390,1.211998,1.033635,1.112612,1.054682,1.834032,...,1.484447,0.819555,0.608719,1.334733,1.475264,1.499739,1.566971,1.491554,0.785321,0.680223
4,서울특별시,중구,회현동,1.216539,1.231600,1.216814,1.264384,1.245211,1.186977,1.185489,...,1.123279,0.813363,0.665930,1.198933,1.253730,1.236836,1.179716,1.232473,0.793768,0.773963

In [20]:
df1.tail()

,PVN,BOR,ADMD,20190201,20190202,20190203,20190204,20190205,20190206,20190207,...,20200522,20200523,20200524,20200525,20200526,20200527,20200528,20200529,20200530,20200531
62,대구광역시,수성구,범물1동,0.755404,0.918263,0.820164,1.043473,1.065493,0.836403,0.834646,...,0.860603,0.915500,0.829252,0.841895,0.949411,0.897434,0.850776,0.964880,0.963330,0.799996
63,대구광역시,수성구,범물2동,1.049858,0.858762,0.885710,0.976652,1.270511,0.813579,0.816370,...,0.877036,0.766203,0.666824,0.751264,0.754635,0.756833,0.706694,0.723095,0.818933,0.795816
64,대구광역시,수성구,고산1동,1.064336,0.940026,0.943638,0.954553,0.989785,0.847491,0.875940,...,0.790165,0.778612,0.665100,0.703047,0.780585,0.745286,0.733123,0.821357,0.862803,0.732357
65,대구광역시,수성구,고산2동,1.076418,1.172479,1.153766,1.556855,1.658221,1.122046,1.105032,...,1.078168,1.093085,1.139640,1.183757,1.077460,1.189024,1.180665,1.133741,1.152602,1.094919
66,대구광역시,수성구,고산3동,0.856071,0.895912,0.924304,0.901465,0.984660,0.803701,0.884377,...,0.729644,0.692439,0.581983,0.629087,0.699269,0.653439,0.700569,0.754452,0.788261,0.567368

In [21]:
df2.head()

,PVN,BOR,ADMD,ANTC_ITEM_LCLS_CD,ANTC_ITEM_LCLS_NM,20190201,20190202,20190203,20190204,20190205,...,20200522,20200523,20200524,20200525,20200526,20200527,20200528,20200529,20200530,20200531
0,서울특별시,중구,소공동,10,식사,0.287643,0.304000,0.275632,0.355523,0.317881,...,0.268470,0.243105,0.327853,0.299879,0.247657,0.265204,0.251100,0.239728,0.230298,0.324881
1,서울특별시,중구,소공동,20,간식,0.185728,0.227291,0.225132,0.238465,0.269207,...,0.195261,0.229224,0.181475,0.173981,0.177090,0.200248,0.195551,0.225265,0.213128,0.191642
2,서울특별시,중구,소공동,30,마실거리,0.383557,0.344574,0.271592,0.308400,0.318957,...,0.394646,0.401531,0.354308,0.411805,0.378491,0.429040,0.421532,0.430289,0.430194,0.374880
3,서울특별시,중구,소공동,40,홈&리빙,0.041739,0.028022,0.017387,0.015014,0.015643,...,0.035964,0.027361,0.027054,0.037556,0.046373,0.025700,0.043245,0.026604,0.042435,0.019790
4,서울특별시,중구,소공동,50,헬스&뷰티,0.081483,0.084229,0.187566,0.057285,0.061882,...,0.086849,0.077277,0.096562,0.064942,0.140060,0.068092,0.075478,0.061774,0.069820,0.070321

In [22]:
df2.tail()

,PVN,BOR,ADMD,ANTC_ITEM_LCLS_CD,ANTC_ITEM_LCLS_NM,20190201,20190202,20190203,20190204,20190205,...,20200522,20200523,20200524,20200525,20200526,20200527,20200528,20200529,20200530,20200531
475,대구광역시,수성구,고산3동,40,홈&리빙,0.013408,0.007657,0.011822,0.015714,0.015756,...,0.017208,0.015695,0.017763,0.015542,0.003279,0.006441,0.012155,0.011351,0.012095,0.034935
476,대구광역시,수성구,고산3동,50,헬스&뷰티,0.029606,0.055773,0.077440,0.066413,0.065260,...,0.054248,0.037031,0.057820,0.032960,0.039889,0.047162,0.048096,0.041842,0.045093,0.051165
477,대구광역시,수성구,고산3동,60,취미&여가활동,0.009117,0.009844,NaN,0.006625,0.015521,...,NaN,0.002942,0.004597,0.005384,0.001369,0.015550,0.005045,0.006376,0.003674,0.005710
478,대구광역시,수성구,고산3동,70,사회활동,0.008831,0.020163,0.009240,0.016661,0.019641,...,0.002892,0.009716,0.009152,0.000234,0.006985,0.003455,0.007637,NaN,0.002242,0.007527
479,대구광역시,수성구,고산3동,80,임신/육아,0.005697,0.006049,0.003683,0.005065,0.006485,...,0.006293,0.005212,0.001097,0.006931,0.005582,0.013035,0.004556,0.006540,0.004017,0.007221

In [23]:
df3.head()

,OPER_DT,PVN,BOR,ADMD,AMT_IND,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P
0,20190201,대구광역시,수성구,고산1동,1.064336,0.450848,0.172221,0.295458,0.023263,0.044679,0.005075,0.004820,0.003637
1,20190201,대구광역시,수성구,고산2동,1.076418,0.457937,0.196274,0.295564,0.005521,0.034056,0.000844,0.008893,0.000913
2,20190201,대구광역시,수성구,고산3동,0.856071,0.359978,0.196602,0.376762,0.013408,0.029606,0.009117,0.008831,0.005697
3,20190201,대구광역시,수성구,두산동,0.724868,0.281969,0.175207,0.363202,0.024235,0.134191,0.000000,0.021196,0.000000
4,20190201,대구광역시,수성구,만촌1동,1.155728,0.400983,0.200454,0.310531,0.038868,0.035427,0.005284,0.005734,0.002719

In [24]:
df3.tail()

,OPER_DT,PVN,BOR,ADMD,AMT_IND,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P
14455,20200531,서울특별시,중구,중림동,1.595038,0.314217,0.221087,0.344307,0.026204,0.070094,0.006347,0.013541,0.004203
14456,20200531,서울특별시,중구,청구동,1.389184,0.276333,0.221216,0.363681,0.053907,0.076963,0.001592,0.000353,0.005955
14457,20200531,서울특별시,중구,필동,0.714265,0.303338,0.187615,0.370371,0.038908,0.079408,0.007826,0.008298,0.004236
14458,20200531,서울특별시,중구,황학동,1.134190,0.264708,0.257387,0.367001,0.029140,0.070770,0.001060,0.003646,0.006287
14459,20200531,서울특별시,중구,회현동,0.773963,0.316750,0.160035,0.410281,0.031188,0.071026,0.000000,0.009057,0.001663